sources:
  - type: feed
    name: Maurycy's blog
    strategy: bookmark
    options:
      url: https://maurycyz.com/index.xml
      interval: 24h

  # Registered source. Other sources are just fire and forget
  - type: url
    name: Google
    strategy: archive
    options:
      url: https://google.com
      interval: 24h

strategies:
  bookmark:
    description: Bookmark only.
    library: disk
    archivers: []
  archive:
    description: Full archival.
    library: disk
    archivers:
      - type: archive.org
      - type: chrome
        options:
          pdf:
            enabled: true
          singlefile:
            enabled: true
          screenshot:
            enabled: true
            resolutions:
              - 1280x720

libraries:
  disk:
    name: Disk
    description: Local storage
    type: disk
    options:
      path: ./data/disk
      compress: true
