sources:
  - type: feed
    name: Maurycy's blog
    url: https://maurycyz.com/index.xml
    options:
      interval: 24h
    strategies:
      - archive

  - type: url
    name: Ahey - A simple pub-sub over web push
    url: https://ahey.io/
    strategies:
      - archive

strategies:
  archive:
    description: Full archival.
    library: warc
    archivers:
      - type: archive.org
      - type: chrome
        options:
          pdf:
            enabled: true
          screenshot:
            enabled: true
            resolutions:
              - width: 1280
                height: 720
          singlefile:
            enabled: true

libraries:
  - name: Archive Box
    type: archivebox
    path: /var/data/archive-box
  - name: WARC
    type: warc
    path: /var/data/warcs
  - name: Disk
    type: disk
    path: /var/data/disk
  - name: blobs
    type: blob
    path: /var/data/blobs
    options:
      compact: true
      backup: true
  - name: oci
    type: oci
    path: https://registry.home.internal
